trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  HEYHACK_API_KEY: $(heyhackApiKey)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12.5'
    addToPath: true

- script: |
    pip install requests
    echo "Start F5 BIG-IP service deployment for arcadia"
    echo "Inicia la autenticacion"
    python 1_AS3_Authentication.py
    if [ $? -eq 0 ]; then
      echo "El valor del token es: $(AUTH_TOKEN)"
    else
      echo "Error en la autenticación, deteniendo el pipeline."
      exit 1
    fi
  displayName: 'Autentica y Almacena Token de Autenticación'

- script: |
    pip install requests
    python 3_AS3_Arcadia_Creation.py
  env:
    AUTH_TOKEN: $(AUTH_TOKEN)
  displayName: 'Run Arcadia deployment'