trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  HEYHACK_API_KEY: $(heyhackApiKey)
  #TARGET_URL: 'https://arcadia.f5latam.app'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install requests
    echo "Start F5 BIG-IP service deployment for arcadia"
    python 3_AS3_Arcadia_Creation.py
    #python heyhack_scan.py
  displayName: 'Run Arcadia deployment'

